repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-ast
      - id: debug-statements
      - id: check-added-large-files
        args: ["--maxkb=200"]

  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        args: ["--max-line-length=120", "--ignore=E203,E241,E302,E305,E402,E501,W503"]
        files: ^server\.py$

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: ["--line-length=120", "--skip-string-normalization"]
        files: ^server\.py$
